# Generated by Django 3.2.3 on 2021-08-19 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20210819_1858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='listing',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='active',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='buyer',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='currentBid',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='watcher',
        ),
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_list', to='auctions.category'),
        ),
        migrations.DeleteModel(
            name='Bid',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
