# Generated by Django 3.2.3 on 2021-08-20 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_alter_listing_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='creator',
        ),
    ]
